#!/usr/bin/python

import http, threading, sys, signal

THREAD_MAX = 4

def main():
    root = sys.argv[1] if len(sys.argv) >= 2 else "./"

    server = http.init()

    def __sigint_handler(sig, frame):
        http.close(server)
        sys.exit(0)

    signal.signal(signal.SIGINT, __sigint_handler)

    for _ in range(THREAD_MAX):
        thread = threading.Thread(target=http.serve, args=[server, root, lambda host, port: print(f"[INFO ::] Listening..")])
        thread.start()

if __name__ == "__main__":
    main()
